/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author sheldon
 */
public class Juego1 extends javax.swing.JFrame {

    /**
     * Creates new form MenuCartas
     */
    public Juego1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCarta1 = new javax.swing.JButton();
        jButtonCarta2 = new javax.swing.JButton();
        jButtonCarta3 = new javax.swing.JButton();
        jButtonCarta4 = new javax.swing.JButton();
        jButtonCarta7 = new javax.swing.JButton();
        jButtonCarta6 = new javax.swing.JButton();
        jButtonCarta5 = new javax.swing.JButton();
        jButtonCarta8 = new javax.swing.JButton();
        jButtonCarta9 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelDerechos = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonCarta10 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCarta1.setText("Fase");
        jButtonCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 880, 60));

        jButtonCarta2.setText("carta 2");
        jButtonCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 260, 120));

        jButtonCarta3.setText("carta 3");
        jButtonCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 260, 120));

        jButtonCarta4.setText("carta 4");
        jButtonCarta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 260, 120));

        jButtonCarta7.setText("carta 7");
        jButtonCarta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 260, 120));

        jButtonCarta6.setText("carta 6");
        jButtonCarta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 260, 120));

        jButtonCarta5.setText("carta 5");
        jButtonCarta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 260, 120));

        jButtonCarta8.setText("carta 8");
        jButtonCarta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 260, 120));

        jButtonCarta9.setText("carta 9");
        jButtonCarta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 260, 120));

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 204));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabelDerechos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDerechos.setText("derechos ");
        getContentPane().add(jLabelDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jButtonRegresar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        jButtonCarta10.setText("carta 1");
        jButtonCarta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarta10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 260, 120));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1067, 539));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta6ActionPerformed
        Carta6 nuevaCarta = new Carta6();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta6ActionPerformed

    private void jButtonCarta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta7ActionPerformed
        Carta7 nuevaCarta = new Carta7();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta7ActionPerformed

    private void jButtonCarta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta4ActionPerformed
        Carta4 nuevaCarta = new Carta4();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta4ActionPerformed

    private void jButtonCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta3ActionPerformed
        Carta3 nuevaCarta = new Carta3();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta3ActionPerformed

    private void jButtonCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta2ActionPerformed
        Carta2 nuevaCarta = new Carta2();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta2ActionPerformed

    private void jButtonCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta1ActionPerformed
        Carta1 nuevaCarta = new Carta1();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta1ActionPerformed

    private void jButtonCarta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta5ActionPerformed
        Carta5 nuevaCarta = new Carta5();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta5ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCarta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta8ActionPerformed
       Carta8 nuevaCarta = new Carta8();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta8ActionPerformed

    private void jButtonCarta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta9ActionPerformed
        Carta9 nuevaCarta = new Carta9();
        nuevaCarta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarta9ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed

        MenuPrincipal regresar = new MenuPrincipal();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonCarta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarta10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCarta10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarta1;
    private javax.swing.JButton jButtonCarta10;
    private javax.swing.JButton jButtonCarta2;
    private javax.swing.JButton jButtonCarta3;
    private javax.swing.JButton jButtonCarta4;
    private javax.swing.JButton jButtonCarta5;
    private javax.swing.JButton jButtonCarta6;
    private javax.swing.JButton jButtonCarta7;
    private javax.swing.JButton jButtonCarta8;
    private javax.swing.JButton jButtonCarta9;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDerechos;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
