/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.GridLayout;

/**
 *
 * @author sheldon
 */
public class MenuPrimigenios extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrimigenios() {
        initComponents();
        this.setLocationRelativeTo(null);
      //  GridLayout gridLayout1 = new GridLayout();

        //this.setLayout(gridLayout1);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelDerechos = new javax.swing.JLabel();
        jButtonPrimigenio2 = new javax.swing.JButton();
        jButtonPrimigenio4 = new javax.swing.JButton();
        jLabelIniciar = new javax.swing.JLabel();
        jLabelNuevo = new javax.swing.JLabel();
        jButtonPrimigenio1 = new javax.swing.JButton();
        jButtonPrimigenio3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 204));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("X");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 20));

        jLabelDerechos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDerechos.setText("derechos ");
        getContentPane().add(jLabelDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jButtonPrimigenio2.setBackground(new java.awt.Color(0, 51, 204));
        jButtonPrimigenio2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrimigenio2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimigenio2.setText("Primigenio2");
        jButtonPrimigenio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimigenio2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrimigenio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 340, 270));

        jButtonPrimigenio4.setBackground(new java.awt.Color(0, 51, 204));
        jButtonPrimigenio4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrimigenio4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimigenio4.setText("Primigenio4");
        jButtonPrimigenio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimigenio4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrimigenio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 340, 270));
        getContentPane().add(jLabelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));
        getContentPane().add(jLabelNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jButtonPrimigenio1.setBackground(new java.awt.Color(0, 51, 204));
        jButtonPrimigenio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrimigenio1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimigenio1.setText("Primigenio1");
        jButtonPrimigenio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimigenio1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrimigenio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 340, 270));

        jButtonPrimigenio3.setBackground(new java.awt.Color(0, 51, 204));
        jButtonPrimigenio3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrimigenio3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimigenio3.setText("Primigenio3");
        jButtonPrimigenio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimigenio3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrimigenio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 340, 270));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoprincipal.jpg"))); // NOI18N
        jLabelFondo.setName(""); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        setSize(new java.awt.Dimension(1062, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonPrimigenio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimigenio2ActionPerformed
        Juego2 regresar = new Juego2();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPrimigenio2ActionPerformed

    private void jButtonPrimigenio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimigenio4ActionPerformed
        Juego4 regresar = new Juego4();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPrimigenio4ActionPerformed

    private void jButtonPrimigenio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimigenio1ActionPerformed
        Juego1 regresar = new Juego1();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPrimigenio1ActionPerformed

    private void jButtonPrimigenio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimigenio3ActionPerformed
        Juego3 regresar = new Juego3();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPrimigenio3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrimigenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrimigenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrimigenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrimigenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrimigenios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrimigenio1;
    private javax.swing.JButton jButtonPrimigenio2;
    private javax.swing.JButton jButtonPrimigenio3;
    private javax.swing.JButton jButtonPrimigenio4;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDerechos;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIniciar;
    private javax.swing.JLabel jLabelNuevo;
    // End of variables declaration//GEN-END:variables
}
